import type { Metadata } from "next";
import { Oswald, Smooch_Sans } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";

// 1. IMPORT NAVBAR COMPONENT
import { Navbar } from "@/components/layout/NavBar";

const oswald = Oswald({ variable: "--font-oswald", subsets: ["latin"] });
const smoochSans = Smooch_Sans({
  variable: "--font-smooch",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${oswald.variable} ${smoochSans.variable} antialiased`}>
        <Providers>
          {/* 2. ADD NAVBAR HERE */}
          <Navbar />

          {/* 3. WRAP CONTENT IN MAIN WITH TOP PADDING (pt-24)
              pt-24 equals "padding-top: 6rem" (approx 96px), providing space for the fixed navbar. */}
          <main className="pt-24 min-h-screen">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
